name: museus
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  line_awesome_flutter: ^3.0.1
  smooth_page_indicator: ^1.0.0
  iconsax: ^0.0.8
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - 'images/'
    - 'images/masp.jpg'
    - 'images/museu1.jpg'
    - 'images/museu2.jpg'
    - 'images/museu3.jpg'

